# Generated by Django 5.0.6 on 2024-06-24 14:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='category/')),
                ('add_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('description', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='post/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.category', verbose_name='category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('user_comments', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('refrence_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.post')),
            ],
        ),
        migrations.CreateModel(
            name='reply_message',
            fields=[
                ('reply_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_reply_message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('refrence_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.comments')),
            ],
        ),
    ]
